FROM golang:latest

ARG APP_NAME
ARG APP_PORT
ARG APP_SERVICE_MODE
ARG APP_DEBUG
ARG RELATIVE_PATH
ARG DATA_SOURCE

ARG WORKPATH="$GOPATH/$RELATIVE_PATH/$APP_NAME"

WORKDIR "$WORKPATH"

ADD . "$WORKPATH"

COPY go.mod .

COPY go.sum .

RUN go test ./...

ENV NAME_APP=$APP_NAME
ENV PORT_APP=$APP_PORT
ENV SERVICE_MODE_APP=$APP_SERVICE_MODE
ENV DEBUG_APP=$APP_DEBUG
ENV DATA_SOURCE_APP=$DATA_SOURCE

RUN go build -o $NAME_APP

ENTRYPOINT ./$NAME_APP -service=$SERVICE_MODE_APP -port=$PORT_APP -debug=$DEBUG_APP
